steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_IMAGE_URL}:${_IMAGE_TAG}', './sample_app/']

#- name: 'ubuntu' 
#  entrypoint: 'bash'
#  args: ['-c', 'echo SECURE_API_TOKEN=$$SECURE_API_TOKEN && echo IMAGE_URL_TAG=${_IMAGE_URL}:${_IMAGE_TAG}']
#  secretEnv: ['SECURE_API_TOKEN', 'SYSDIG_API_URL']

#- name: 'koton00beng/sysdig-cli:latest'
#  args: [ '--apiurl', '$$SYSDIG_API_URL', '${_IMAGE_URL}:${_IMAGE_TAG}', 'cat test.txt' ]
#  secretEnv: ['SECURE_API_TOKEN', 'SYSDIG_API_URL']

- name: 'ubuntu'
  args:
    - |
      ls -la;
      curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/linux/amd64/sysdig-cli-scanner";
      chmod +x ./sysdig-cli-scanner;
      ./sysdig-cli-scanner --apiurl $SYSDIG_API_URL --console-log '${_IMAGE_URL}:${_IMAGE_TAG}'
      
  secretEnv: ['SECURE_API_TOKEN', 'SYSDIG_API_URL']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_IMAGE_URL}:${_IMAGE_TAG}']

availableSecrets:
  secretManager:
  - versionName: projects/gcr-test1-428416/secrets/sysdig_token/versions/1
    env: 'SECURE_API_TOKEN'
  - versionName: projects/gcr-test1-428416/secrets/sysdig_api_url/versions/1
    env: 'SYSDIG_API_URL'

substitutions:
  _IMAGE_URL: 'us-east1-docker.pkg.dev/gcr-test1-428416/golang-sysdig-cli'
  _IMAGE_TAG: 'latest'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 900s