# Use an official base image that includes curl, build #4
FROM ubuntu:latest

WORKDIR /sysdig
RUN apt-get update && apt-get install -y curl
RUN curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/linux/amd64/sysdig-cli-scanner"
RUN chmod +x ./sysdig-cli-scanner

ENTRYPOINT ["./sysdig-cli-scanner"]
CMD ["--help"] 
